#!/bin/bash
# Extract Batch of DICOMS
# ------------------------------------------------------------------------------------------------------------
# Default Arguments
me=$(whoami)
today=$(date)

r="/Volumes/CFMI-CFS/mnt/CFMI-DICOMS/"
o="/Volumes/CFMI-CFS/sync/ADS/data/mri/dicoms"
f="$o/ADS-MRI-DATES.txt"

# Get Meta Data For Extraction
echo -e "\n📃   Extracting Subject IDS and Scan Dates from $f\n"
subject=$(awk '{print $1}' $f)
scandate=($(awk '{print $2}' $f))
session=($(awk '{print $3}' $f))
# ------------------------------------------------------------------------------------------------------------
# Run Batch (do this in parallel you dope!) --> address TODO in fetch dicom for subject parsing
counter=0
for s in $subject; do
    # Get Session Label
    ss=${session[$counter]}
	# Extract Year, Month and Day
	datestr=${scandate[$counter]}
	SAVEIFS=${IFS} && IFS='-' read -ra datestr <<< "$datestr"
	year="${datestr[0]}"
	mon="${datestr[1]}"
	day="${datestr[2]}"
	IFS=${SAVEIFS}
	fetch-dicom -s ${s} -o ${o}/wave-${ss} -y $year -m $mon -d $day 
	# Pull dicom for subject
	counter=$((counter+1))
done
echo -e '✅  job complete - now go publish some papers\n\n'

